pipelines:
  branches:
    development:
      - step:
          name: Deploy to Staging
          deployment: staging
          script:
            - pipe: atlassian/sftp-deploy:0.5.8
              variables:
                USER: $SFTP_USERNAME
                SERVER: $SFTP_HOST
                REMOTE_PATH: $SFTP_REMOTE_PATH
                PASSWORD: $SFTP_PASSWORD
                EXTRA_ARGS: '-P $SFTP_PORT'